#:schema node_modules/wrangler/config-schema.json
name = "lena-student-web"
main = "build/server/index.js"
assets = { directory = "build/client", binding = "ASSETS" }
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "lena-student-web-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "lena-student-web-prod"
vars = { ENVIRONMENT = "production" }

# Environment variables (add your actual values via CLI or dashboard)
[vars]
VITE_LENA_API_URL = "https://test.lena.africa"
NODE_ENV = "development"
