# Cloudflare Pages Configuration
# Alternative to Workers - for testing Pages deployment

name = "lena-student-web"
compatibility_date = "2025-04-04"

# Required for Pages - specifies where the built static files are
pages_build_output_dir = "build/client"

[env.production.vars]
NODE_ENV = "production"

# Secrets should be set via: 
# npx wrangler pages secret put VITE_LENA_API_URL --project-name=lena-student-web-pages

# Pages Functions directory: functions/
# Static assets directory: build/client
