name = "lena-student-web"
main = "cloudflare/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets served by the Worker
[assets]
directory = "./build/client"

# Environment variables (will be overridden by Dashboard)
[vars]
NODE_ENV = "development"
VITE_LENA_API_URL = "https://test.lena.africa"
